export const HOME = '/home'
export const SIGN_UP = '/signup'
export const LOGIN = '/login'
export const LOGOUT = '/logout'
export const PROFILE = '/auth/users/'
export const RESET = '/password-reset'
export const NEW = '/posts/new'
export const POST = '/posts'
